# Generated by Django 6.0.2 on 2026-05-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
