# Generated by Django 6.0.2 on 2026-05-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('classroom', 'Classroom'), ('hostel', 'Hostel'), ('network', 'Network / Wi-Fi'), ('electricity', 'Electricity'), ('cleanliness', 'Cleanliness'), ('transport', 'Transport')], max_length=20),
        ),
    ]
